include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: false
  exclude:
    - "**/**.g.dart"
    - "**/**.tailor.dart"
    - "bricks/**/__brick__/**"
    - "lib/l10n/**"
  errors:
    invalid_assignment: ignore
    invalid_annotation_target: ignore
    todo: info
    prefer_final_fields: ignore
    constant_identifier_names: ignore
    prefer_single_quotes: ignore
  plugins:
    - dart_code_metrics

linter:
  rules:
    # relative imports
    always_use_package_imports: true
    prefer_relative_imports: false
    prefer_single_quotes: true

    # other
    dangling_library_doc_comments: false
    sort_pub_dependencies: false
    unnecessary_library_directive: false
    prefer_const_constructors: true
    implementation_imports: true
    prefer_final_in_for_each: true
    prefer_if_elements_to_conditional_expressions: true


dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    halstead-volume: 150
    lines-of-code: 100
    maintainability-index: 50
    maximum-nesting-level: 5
    number-of-methods: 10
    number-of-parameters: 8
    source-lines-of-code: 100
    weight-of-class: 0.33

  metrics-exclude:
    - test/**

  rules:
    - avoid-cascade-after-if-null
    - avoid-double-slash-imports
    - avoid-duplicate-exports
    - avoid-global-state
    - avoid-missing-enum-constant-in-map
    - avoid-redundant-async
    - avoid-throw-in-catch-block
   # - avoid-top-level-members-in-tests
    - avoid-unnecessary-conditionals
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - binary-expression-operand-order
    - list-all-equatable-fields
    - member-ordering:
        order:
          - public-fields
          - private-fields
          - constructors
          - close-method
          - dispose-method
        widgets-order:
          - constructor
          - init-state-method
          - did-change-dependencies-method
          - did-update-widget-method
          - dispose-method
          - build-method
    - no-boolean-literal-compare
    - no-equal-then-else
    - no-object-declaration
    - prefer-commenting-analyzer-ignores
    - prefer-enums-by-name
    - prefer-first
    - prefer-immediate-return
    - prefer-iterable-of
    - prefer-last
    - prefer-trailing-comma
    - always-remove-listener
    - avoid-border-all
    - avoid-unnecessary-setstate
    - avoid-expanded-as-spacer
    - avoid-wrapping-in-padding
    - check-for-equals-in-render-object-setters
    - consistent-update-render-object
    - prefer-const-border-radius
    - prefer-correct-edge-insets-constructor
    - prefer-using-list-view
